package com.huckor.isoparser;

import java.util.HashMap;
import java.util.Map;

public class AppConstants {
    public static Map<Integer, String> isoFieldNames;
    static {
        isoFieldNames = new HashMap<>();
        isoFieldNames.put(2, "Primary account number (PAN)");
        isoFieldNames.put(3, "Processing Code");
        isoFieldNames.put(4, "Amount Transaction");
        isoFieldNames.put(5, "Amount, settlement");
        isoFieldNames.put(6, "Amount, cardholder billing");
        isoFieldNames.put(7, "Transmission date & time");
        isoFieldNames.put(8, "Amount, cardholder billing fee");
        isoFieldNames.put(9, "Conversion rate, settlement");
        isoFieldNames.put(10, "Conversion rate, cardholder billing");
        isoFieldNames.put(11, "System trace audit number (STAN)");
        isoFieldNames.put(12, "Local transaction time");
        isoFieldNames.put(13, "Local transaction date");
        isoFieldNames.put(14, "Expiration date");
        isoFieldNames.put(15, "Settlement date");
        isoFieldNames.put(16, "Currency conversion date");
        isoFieldNames.put(17, "Capture date");
        isoFieldNames.put(18, "Merchant type, or merchant category code");
        isoFieldNames.put(19, "Acquiring institution (country code)");
        isoFieldNames.put(20, "PAN extended (country code)");
        isoFieldNames.put(21, "Forwarding institution (country code)");
        isoFieldNames.put(22, "Point of service entry mode");
        isoFieldNames.put(23, "Application PAN sequence number");
        isoFieldNames.put(24, "Network international identifier (NII)");
        isoFieldNames.put(25, "Point of service condition code");
        isoFieldNames.put(26, "Point of service capture code");
        isoFieldNames.put(27, "Authorizing identification response length");
        isoFieldNames.put(28, "Amount, transaction fee");
        isoFieldNames.put(29, "Amount, settlement fee");
        isoFieldNames.put(30, "Amount, transaction processing fee");
        isoFieldNames.put(31, "Amount, settlement processing fee");
        isoFieldNames.put(32, "Acquiring institution identification code");
        isoFieldNames.put(33, "Forwarding institution identification code");
        isoFieldNames.put(34, "Primary account number, extended");
        isoFieldNames.put(35, "Track 2 data");
        isoFieldNames.put(36, "Track 3 data");
        isoFieldNames.put(37, "Retrieval reference number");
        isoFieldNames.put(38, "Authorization identification response");
        isoFieldNames.put(39, "Response code");
        isoFieldNames.put(40, "Service restriction code");
        isoFieldNames.put(41, "Card acceptor terminal identification");
        isoFieldNames.put(42, "Card acceptor identification code");
        isoFieldNames.put(43, "Card acceptor name/location");
        isoFieldNames.put(44, "Additional response data");
        isoFieldNames.put(45, "Track 1 data");
        isoFieldNames.put(46, "Additional data (ISO)");
        isoFieldNames.put(47, "Additional data (national)");
        isoFieldNames.put(48, "Additional data (private)");
        isoFieldNames.put(49, "Currency code, transaction");
        isoFieldNames.put(50, "Currency code, settlement");
        isoFieldNames.put(51, "Currency code, cardholder billing");
        isoFieldNames.put(52, "Personal identification number data");
        isoFieldNames.put(53, "Security related control information");
        isoFieldNames.put(54, "Additional amounts");
        isoFieldNames.put(55, "ICC data");
        isoFieldNames.put(56, "Reserved (ISO)");
        isoFieldNames.put(57, "Reserved (national)");
        isoFieldNames.put(58, "Reserved (national)");
        isoFieldNames.put(59, "Reserved (national)");
        isoFieldNames.put(60, "Reserved (national)");
        isoFieldNames.put(61, "Reserved (private)");
        isoFieldNames.put(62, "Reserved (private)");
        isoFieldNames.put(63, "Reserved (private)");
        isoFieldNames.put(64, "Message authentication code (MAC)");
        isoFieldNames.put(65, "Extended bitmap indicator");
        isoFieldNames.put(66, "Settlement code");
        isoFieldNames.put(67, "Extended payment code");
        isoFieldNames.put(68, "Receiving institution country code");
        isoFieldNames.put(69, "Settlement institution country code");
        isoFieldNames.put(70, "Network management information code");
        isoFieldNames.put(71, "Message number");
        isoFieldNames.put(72, "Last message's number");
        isoFieldNames.put(73, "Action date (YYMMDD)");
        isoFieldNames.put(74, "Number of credits");
        isoFieldNames.put(75, "Credits, reversal number");
        isoFieldNames.put(76, "Number of debits");
        isoFieldNames.put(77, "Debits, reversal number");
        isoFieldNames.put(78, "Transfer number");
        isoFieldNames.put(79, "Transfer, reversal number");
        isoFieldNames.put(80, "Number of inquiries");
        isoFieldNames.put(81, "Number of authorizations");
        isoFieldNames.put(82, "Credits, processing fee amount");
        isoFieldNames.put(83, "Credits, transaction fee amount");
        isoFieldNames.put(84, "Debits, processing fee amount");
        isoFieldNames.put(85, "Debits, transaction fee amount");
        isoFieldNames.put(86, "Total amount of credits");
        isoFieldNames.put(87, "Credits, reversal amount");
        isoFieldNames.put(88, "Total amount of debits");
        isoFieldNames.put(89, "Debits, reversal amount");
        isoFieldNames.put(90, "Original data elements");
        isoFieldNames.put(91, "File update code");
        isoFieldNames.put(92, "File security code");
        isoFieldNames.put(93, "Response indicator");
        isoFieldNames.put(94, "Service indicator");
        isoFieldNames.put(95, "Replacement amounts");
        isoFieldNames.put(96, "Message security code");
        isoFieldNames.put(97, "Net settlement amount");
        isoFieldNames.put(98, "Payee");
        isoFieldNames.put(99, "Settlement institution identification code");
        isoFieldNames.put(100, "Receiving institution identification code");
        isoFieldNames.put(101, "File name");
        isoFieldNames.put(102, "Account identification 1");
        isoFieldNames.put(103, "Account identification 2");
        isoFieldNames.put(104, "Transaction description");
        isoFieldNames.put(105, "Reserved for ISO use");
        isoFieldNames.put(106, "Reserved for ISO use");
        isoFieldNames.put(107, "Reserved for ISO use");
        isoFieldNames.put(108, "Reserved for ISO use");
        isoFieldNames.put(109, "Reserved for ISO use");
        isoFieldNames.put(110, "Reserved for ISO use");
        isoFieldNames.put(111, "Reserved for ISO use");
        isoFieldNames.put(112, "Reserved for national use");
        isoFieldNames.put(113, "Reserved for national use");
        isoFieldNames.put(114, "Reserved for national use");
        isoFieldNames.put(115, "Reserved for national use");
        isoFieldNames.put(116, "Reserved for national use");
        isoFieldNames.put(117, "Reserved for national use");
        isoFieldNames.put(118, "Reserved for national use");
        isoFieldNames.put(119, "Reserved for national use");
        isoFieldNames.put(120, "Reserved for private use");
        isoFieldNames.put(121, "Reserved for private use");
        isoFieldNames.put(122, "Reserved for private use");
        isoFieldNames.put(123, "Reserved for private use");
        isoFieldNames.put(124, "Reserved for private use");
        isoFieldNames.put(125, "Reserved for private use");
        isoFieldNames.put(126, "Reserved for private use");
        isoFieldNames.put(127, "Reserved for private use");
        isoFieldNames.put(128, "Message authentication code");
    }
}
