name: Build app

on: [push]

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Setup JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '19'
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Gradle build and test
        run: ./gradlew build test
      - name: Create package using jlink
        run: ./gradlew jlink
